export const REQUEST_SEMINARS = 'REQUEST_SEMINARS';
export const REQUEST_SEMINARS_SUCCESS = 'REQUEST_SEMINARS_SUCCESS';
export const REQUEST_SEMINARS_ERROR = 'REQUEST_SEMINARS_ERROR';
export const ADD_SEMINAR = 'ADD_SEMINAR';
export const ADD_SEMINAR_SUCCESS = 'ADD_SEMINAR_SUCCESS';
export const ADD_SEMINAR_ERROR = 'ADD_SEMINAR_ERROR';
export const DELETE_SEMINAR = 'DELETE_SEMINAR';
export const DELETE_SEMINAR_SUCCESS = 'DELETE_SEMINAR_SUCCESS';
export const DELETE_SEMINAR_ERROR = 'DELETE_SEMINAR_ERROR';
export const UPDATE_SEMINAR = 'UPDATE_SEMINAR';
export const UPDATE_SEMINAR_SUCCESS = 'UPDATE_SEMINAR_SUCCESS';
export const UPDATE_SEMINAR_ERROR = 'UPDATE_SEMINAR_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

